### ISSUE TITLE
Proposal 1 - Sketches

### ISSUE THREAD

**Issue by ColinGJohnson** [RyanBarclay/Seng310-Workboard#10]
Add sketches for Proposal 1

**Comment by RyanBarclay** [comment]
Working on wireframes mobile workup, specifically one with the calendar to tidy it up.

**Comment by RyanBarclay** [comment]
Then will transfer into doc "Project proposal 1"

**Comment by nicolepeverley** [comment]
We will probably need these sketches ready before we fully write up the solution 🚀

**Comment by RyanBarclay** [comment]
Finished filling out calendar wireframe [Here](https://drive.google.com/file/d/1AS2zUWe-Y0f7_cIIMsyhqmNR8cNHnVQG/view?usp=sharing)

**Comment by RyanBarclay** [comment]
Waiting for feedback on new design add-ons. If we're all good then we can close and integrate with docs

**Comment by nicolepeverley** [comment]
Looks good to me 👍
