### ISSUE TITLE
Sign off on Assignment 1

### ISSUE THREAD

**Issue by ColinGJohnson** [RyanBarclay/Seng310-Workboard#14]
When all tasks for A1 is done, check your name off here

- [x] Colin
- [x] Ryan
- [x] Dominique
- [x] Nicole
- [x] Kaiden
- [x] Stephen

**Comment by iamthestevie** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/58121489/93539066-91d40c80-f904-11ea-818c-5943f528d5b8.png">

**Comment by iamthestevie** [comment]
![Uploading image.png…]()

**Comment by iamthestevie** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/58121489/93539943-04de8280-f907-11ea-9456-b021d0afeea8.png">

**Comment by RyanBarclay** [comment]
Refer to post when handing in https://seng310-202009.slack.com/archives/C0194A3MSK1/p1600455613012900
