### ISSUE TITLE
Proposal 1 - Content

### ISSUE THREAD

**Issue by FlyteWizard** [RyanBarclay/Seng310-Workboard#15]
Create content for Proposal 1

- [x] Problem
- [x] Motivation
- [x] Solution
- [x] References

**Comment by RyanBarclay** [comment]
Working on basics for Soln part

**Comment by nicolepeverley** [comment]
Added content to Solution part and had to cut out other parts to keep below 500 word count. Could use some review!

**Comment by RyanBarclay** [comment]
Adding in map wireframe and added a small description to account for word count.

- [ ] waiting for review
