### ISSUE TITLE
Project Proposal 1 - Implied Consent Form (Fill Out)

### ISSUE THREAD

**Issue by FlyteWizard** [RyanBarclay/Seng310-Workboard#28]
Document: https://docs.google.com/document/d/1D7UY4hiyu8FrPAVGR_aBO4mqcRCU8Rjv
Google Doc (Edit This Document): https://docs.google.com/document/d/1viMk3iR6L114Bs2QzoKJInM1gscpkq_0fUWuOyku0Ps/edit

**Comment by RyanBarclay** [comment]
https://docs.google.com/document/d/1D7UY4hiyu8FrPAVGR_aBO4mqcRCU8Rjv/edit

**Comment by RyanBarclay** [comment]
Needs two people to sign off before formatting and submission.
