### ISSUE TITLE
Proposal 1 - WP Page Content

### ISSUE THREAD

**Issue by FlyteWizard** [RyanBarclay/Seng310-Workboard#4]
Add Project Idea 2 to the WP Page: https://onlineacademiccommunity.uvic.ca/ryancolindominiquekaidennicolestephen/?page_id=115&preview=true

**Comment by RyanBarclay** [comment]
I don't know how to make the "Figure _x_"  [4 -> 7] the same font and colour as [1 ->3]

**Comment by nicolepeverley** [comment]
> I don't know how to make the "Figure _x_" [4 -> 7] the same font and colour as [1 ->3]

I think it looks the same to me now!

**Comment by FlyteWizard** [comment]
If you click "edit" on an image you get the option to add alternate text and a caption. Figure 1-3 had a caption, but 4-8 didn't. I added the caption for figure 4-8.
